// Draw the two autogenerated MC Dalitz-plot macros without editing their
// bin-content assignments.  The histogram is cloned after each macro runs.
#include <algorithm>
#include <stdexcept>
#include <vector>

#include "TBox.h"
#include "TCanvas.h"
#include "TFile.h"
#include "TList.h"
#include "TPad.h"
#include "TROOT.h"
#include "TKey.h"
#include "TStyle.h"
#include "TSystem.h"
#include "TH2.h"
#include "TH1.h"

namespace {
TString ExtractorPath()
{
  const char *helpersDirectory = gSystem->Getenv("YAZI_ROOT_HELPERS_DIR");
  if (!helpersDirectory)
    throw std::runtime_error("YAZI_ROOT_HELPERS_DIR is not set");

  const TString extractor = Form("%s/extract_mc_2D_histogram.C", helpersDirectory);
  if (gSystem->AccessPathName(extractor))
    throw std::runtime_error(Form("Could not find %s", extractor.Data()));
  return extractor;
}

TH2 *LoadHistogram(const char *macroPath, const char *cloneName,
                   const char *outputFile, std::vector<TBox *> &boxes)
{
  const char *rootSys = gSystem->Getenv("ROOTSYS");
  if (!rootSys)
    throw std::runtime_error("ROOTSYS is not set");

  const TString extractor = ExtractorPath();
  const TString command = Form(
      "\"%s/bin/root\" -l -b -q '%s(\"%s\",\"%s\")'",
      rootSys, extractor.Data(), macroPath, outputFile);
  if (gSystem->Exec(command) != 0)
    throw std::runtime_error(Form("Failed to extract histogram from %s", macroPath));

  TFile input(outputFile, "READ");
  TH2 *source = dynamic_cast<TH2 *>(input.Get("mc2D"));
  if (!source) {
    input.Close();
    gSystem->Unlink(outputFile);
    return nullptr;
  }

  TH2 *histogram = dynamic_cast<TH2 *>(source->Clone(cloneName));
  histogram->SetDirectory(nullptr);

  TIter nextKey(input.GetListOfKeys());
  while (TKey *key = dynamic_cast<TKey *>(nextKey())) {
    if (!TString(key->GetName()).BeginsWith("comparison_box_"))
      continue;
    TBox *box = dynamic_cast<TBox *>(input.Get(key->GetName()));
    if (box)
      boxes.push_back(dynamic_cast<TBox *>(box->Clone()));
  }
  input.Close();
  gSystem->Unlink(outputFile);
  return histogram;
}

void ConfigurePanel(TH2 *histogram, const bool showXaxis,
                    const double yTitleOffset,
                    const std::vector<TBox *> &boxes)
{
  histogram->GetXaxis()->SetTitle("m^{2}(K#pi) [GeV^{2}]");
  histogram->GetXaxis()->SetTitleSize(0.055);
  histogram->GetXaxis()->SetLabelSize(0.045);
  histogram->GetXaxis()->SetTitleOffset(showXaxis ? 0.90 : 1.0);
  histogram->GetXaxis()->SetLabelOffset(showXaxis ? 0.005 : 999.0);
  if (!showXaxis)
    histogram->GetXaxis()->SetTitleOffset(999.0);

  histogram->GetYaxis()->SetTitleSize(0.055);
  histogram->GetYaxis()->SetLabelSize(0.045);
  histogram->GetYaxis()->SetTitleOffset(yTitleOffset);
  histogram->GetZaxis()->SetLabelSize(0.040);

  histogram->Draw("COLZ");
  for (TBox *box : boxes)
    box->Draw("same");
}

TPad *LoadMainPad(const char *macroPath, const char *cloneName,
                  const char *outputFile)
{
  const char *rootSys = gSystem->Getenv("ROOTSYS");
  if (!rootSys)
    throw std::runtime_error("ROOTSYS is not set");
  const TString extractor = ExtractorPath();
  const TString command = Form(
      "\"%s/bin/root\" -l -b -q '%s(\"%s\",\"%s\")'",
      rootSys, extractor.Data(), macroPath, outputFile);
  if (gSystem->Exec(command) != 0)
    throw std::runtime_error(Form("Failed to extract plot from %s", macroPath));

  TFile input(outputFile, "READ");
  TPad *source = dynamic_cast<TPad *>(input.Get("mainPad"));
  if (!source) {
    input.Close();
    gSystem->Unlink(outputFile);
    return nullptr;
  }
  TPad *pad = dynamic_cast<TPad *>(source->Clone(cloneName));
  input.Close();
  gSystem->Unlink(outputFile);
  return pad;
}

TH1 *FindTH1(TPad *pad)
{
  TIter next(pad->GetListOfPrimitives());
  while (TObject *object = next()) {
    if (TH1 *histogram = dynamic_cast<TH1 *>(object))
      return histogram;
    if (TPad *subpad = dynamic_cast<TPad *>(object)) {
      if (TH1 *histogram = FindTH1(subpad))
        return histogram;
    }
  }
  return nullptr;
}

void Configure1DPanel(TPad *pad, const double xlow, const double ylow,
                      const double xhigh, const double yhigh,
                      const bool showXaxis, const double padWidth)
{
  constexpr double leftGutter = 0.14;
  constexpr double rightGutter = 0.06;
  pad->SetPad(xlow, ylow, xhigh, yhigh);
  pad->SetLeftMargin(leftGutter / padWidth);
  pad->SetRightMargin(rightGutter / padWidth);
  pad->SetTopMargin(showXaxis ? 0.03 : 0.08);
  pad->SetBottomMargin(showXaxis ? 0.13 : 0.03);
  if (TH1 *histogram = FindTH1(pad)) {
    histogram->GetXaxis()->SetLabelOffset(showXaxis ? 0.005 : 999.0);
    histogram->GetXaxis()->SetTitleOffset(showXaxis ? 0.95 : 999.0);
    histogram->GetXaxis()->SetLabelSize(0.045);
    histogram->GetXaxis()->SetTitleSize(0.055);
    histogram->GetYaxis()->SetTitleOffset(0.80 / padWidth);
    histogram->GetYaxis()->SetLabelSize(0.045);
    histogram->GetYaxis()->SetTitleSize(0.055);
  }
}
} // namespace

void compare_2D_autogenerated(const char *topMacro, const char *bottomMacro,
                              const char *outputStem = "two_panel_2D",
                              const bool saveOutput = false)
{
  const TString temporaryDirectory = gSystem->TempDirectory();
  const TString psi2SFile = Form("%s/mc_psi2S_%d.root", temporaryDirectory.Data(),
                                 gSystem->GetPid());
  const TString jpsiFile = Form("%s/mc_jpsi_%d.root", temporaryDirectory.Data(),
                                gSystem->GetPid());
  std::vector<TBox *> topBoxes;
  std::vector<TBox *> bottomBoxes;
  TH2 *psi2S = LoadHistogram(topMacro, "top_histogram", psi2SFile.Data(), topBoxes);
  TH2 *jpsi = LoadHistogram(bottomMacro, "bottom_histogram", jpsiFile.Data(), bottomBoxes);
  if (!psi2S || !jpsi)
    throw std::runtime_error("compare_2D_autogenerated requires two TH2 macros");

  const double commonXmin =
      std::min(psi2S->GetXaxis()->GetXmin(), jpsi->GetXaxis()->GetXmin());
  const double commonXmax =
      std::max(psi2S->GetXaxis()->GetXmax(), jpsi->GetXaxis()->GetXmax());
  const double commonXwidth = commonXmax - commonXmin;

  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  // Square canvas for use in a 1:1 slide-content area.
  TCanvas *canvas = new TCanvas("mc_2D_comparison", "", 1000, 1000);

  // Map each native x range into one common canvas coordinate system.  This
  // keeps both histogram bins and annotations such as TBox slice boundaries
  // at their physical x positions, even if either macro has a reduced range.
  constexpr double leftGutter = 0.14;
  constexpr double rightGutter = 0.16;
  constexpr double yTitleOffset = 0.80;
  const double commonFrameWidth = 1.0 - leftGutter - rightGutter;
  const auto frameCoordinate = [&](const double x) {
    return leftGutter + (x - commonXmin) / commonXwidth * commonFrameWidth;
  };
  const auto panelLeft = [&](const TH2 *histogram) {
    return frameCoordinate(histogram->GetXaxis()->GetXmin()) - leftGutter;
  };
  const auto panelRight = [&](const TH2 *histogram) {
    return frameCoordinate(histogram->GetXaxis()->GetXmax()) + rightGutter;
  };

  const double topLeft = panelLeft(psi2S);
  const double topRight = panelRight(psi2S);
  const double topWidth = topRight - topLeft;
  TPad *top = new TPad("top_pad", "", topLeft, 0.50, topRight, 1.0);
  top->SetLeftMargin(leftGutter / topWidth);
  top->SetRightMargin(rightGutter / topWidth);
  top->SetTopMargin(0.08);
  top->SetBottomMargin(0.03);
  top->Draw();
  top->cd();
  top->SetLogz();
  // ROOT measures vertical-title offsets relative to the pad width.
  ConfigurePanel(psi2S, false, yTitleOffset / topWidth, topBoxes);

  canvas->cd();
  const double bottomLeft = panelLeft(jpsi);
  const double bottomRight = panelRight(jpsi);
  const double bottomWidth = bottomRight - bottomLeft;
  TPad *bottom = new TPad("bottom_pad", "", bottomLeft, 0.0, bottomRight, 0.50);
  bottom->SetLeftMargin(leftGutter / bottomWidth);
  bottom->SetRightMargin(rightGutter / bottomWidth);
  bottom->SetTopMargin(0.03);
  bottom->SetBottomMargin(0.13);
  bottom->Draw();
  bottom->cd();
  bottom->SetLogz();
  ConfigurePanel(jpsi, true, yTitleOffset / bottomWidth, bottomBoxes);

  if (saveOutput) {
    canvas->SaveAs(Form("%s.pdf", outputStem));
    canvas->SaveAs(Form("%s.png", outputStem));
  }
}

void compare_1D_autogenerated(const char *topMacro, const char *bottomMacro)
{
  const TString temporaryDirectory = gSystem->TempDirectory();
  const TString topFile = Form("%s/plot_top_%d.root", temporaryDirectory.Data(),
                               gSystem->GetPid());
  const TString bottomFile = Form("%s/plot_bottom_%d.root", temporaryDirectory.Data(),
                                  gSystem->GetPid());
  TPad *top = LoadMainPad(topMacro, "top_1D_pad", topFile.Data());
  TPad *bottom = LoadMainPad(bottomMacro, "bottom_1D_pad", bottomFile.Data());
  if (!top || !bottom)
    throw std::runtime_error("compare_1D_autogenerated requires two fit/pull TH1 macros");
  TH1 *topHistogram = FindTH1(top);
  TH1 *bottomHistogram = FindTH1(bottom);
  if (!topHistogram || !bottomHistogram)
    throw std::runtime_error("Could not locate the main TH1 in both fit panels");

  const double commonXmin = std::min(topHistogram->GetXaxis()->GetXmin(),
                                     bottomHistogram->GetXaxis()->GetXmin());
  const double commonXmax = std::max(topHistogram->GetXaxis()->GetXmax(),
                                     bottomHistogram->GetXaxis()->GetXmax());
  constexpr double leftGutter = 0.14;
  constexpr double rightGutter = 0.06;
  const double commonFrameWidth = 1.0 - leftGutter - rightGutter;
  const auto frameCoordinate = [&](const double x) {
    return leftGutter + (x - commonXmin) / (commonXmax - commonXmin) * commonFrameWidth;
  };
  const auto panelLeft = [&](const TH1 *histogram) {
    return frameCoordinate(histogram->GetXaxis()->GetXmin()) - leftGutter;
  };
  const auto panelRight = [&](const TH1 *histogram) {
    return frameCoordinate(histogram->GetXaxis()->GetXmax()) + rightGutter;
  };
  const double topLeft = panelLeft(topHistogram);
  const double topRight = panelRight(topHistogram);
  const double bottomLeft = panelLeft(bottomHistogram);
  const double bottomRight = panelRight(bottomHistogram);

  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  TCanvas *canvas = new TCanvas("comparison_1D", "", 1000, 1000);
  Configure1DPanel(top, topLeft, 0.50, topRight, 1.0, false, topRight - topLeft);
  Configure1DPanel(bottom, bottomLeft, 0.0, bottomRight, 0.50, true,
                   bottomRight - bottomLeft);
  canvas->cd();
  top->Draw();
  bottom->Draw();
  canvas->Modified();
  canvas->Update();
}

void compare_autogenerated(const char *topMacro, const char *bottomMacro)
{
  const TString topName = gSystem->BaseName(topMacro);
  const TString bottomName = gSystem->BaseName(bottomMacro);
  if (topName.BeginsWith("h_") && bottomName.BeginsWith("h_"))
    compare_1D_autogenerated(topMacro, bottomMacro);
  else
    compare_2D_autogenerated(topMacro, bottomMacro);
}
