// Display one autogenerated ROOT macro with a user-defined main-panel zoom.
// Only its function declaration is read; histogram-bin assignments are never
// parsed or modified.
#include <fstream>
#include <stdexcept>
#include <string>

#include "TCanvas.h"
#include "TList.h"
#include "TPad.h"
#include "TROOT.h"
#include "TH1.h"

namespace {
std::string MacroFunctionName(const char *path)
{
  std::ifstream macro(path);
  std::string line;
  for (int lineCount = 0; lineCount < 20 && std::getline(macro, line); ++lineCount) {
    const std::size_t declaration = line.find("void ");
    if (declaration == std::string::npos)
      continue;
    const std::size_t nameBegin = declaration + 5;
    const std::size_t nameEnd = line.find('(', nameBegin);
    if (nameEnd != std::string::npos)
      return line.substr(nameBegin, nameEnd - nameBegin);
  }
  throw std::runtime_error(Form("Could not identify macro function in %s", path));
}

TH1 *FindHistogram(TPad *pad)
{
  TIter next(pad->GetListOfPrimitives());
  while (TObject *object = next()) {
    if (TH1 *histogram = dynamic_cast<TH1 *>(object))
      return histogram;
    if (TPad *subpad = dynamic_cast<TPad *>(object)) {
      if (TH1 *histogram = FindHistogram(subpad))
        return histogram;
    }
  }
  return nullptr;
}
} // namespace

void display_zoomed_autogenerated(const char *inputMacro, const double xmin,
                                  const double ymin, const double xmax,
                                  const double ymax)
{
  if (xmin >= xmax || ymin >= ymax)
    throw std::runtime_error("Zoom limits must satisfy xmin < xmax and ymin < ymax");

  const std::string functionName = MacroFunctionName(inputMacro);
  gROOT->LoadMacro(inputMacro);
  gROOT->ProcessLine(Form("%s()", functionName.c_str()));

  TCanvas *canvas = dynamic_cast<TCanvas *>(gROOT->GetListOfCanvases()->Last());
  if (!canvas)
    throw std::runtime_error("The input macro did not create a canvas");

  // For generated fit plots, zoom only pad1 and leave a pull pad untouched.
  TPad *mainPad = dynamic_cast<TPad *>(canvas->GetListOfPrimitives()->FindObject("pad1"));
  if (!mainPad) {
    mainPad = canvas;
  } else {
    // A generated TH1 fit plot has pad1 for the distribution and pad2 for
    // pulls. Show only the distribution, enlarged to the whole canvas.
    TPad *pullPad = dynamic_cast<TPad *>(canvas->GetListOfPrimitives()->FindObject("pad2"));
    if (pullPad) {
      canvas->GetListOfPrimitives()->Remove(pullPad);
      delete pullPad;
    }
    mainPad->SetPad(0.0, 0.0, 1.0, 1.0);
    mainPad->SetTopMargin(0.08);
    mainPad->SetBottomMargin(0.13);
  }
  TH1 *histogram = FindHistogram(mainPad);
  if (!histogram)
    throw std::runtime_error("Could not locate the main histogram");

  histogram->GetXaxis()->SetRangeUser(xmin, xmax);
  histogram->GetYaxis()->SetRangeUser(ymin, ymax);
  // Generated macros set a pad range before drawing. Update that transform
  // as well, otherwise ROOT retains the original visible viewport.
  mainPad->Range(xmin, ymin, xmax, ymax);
  mainPad->Modified();
  canvas->Modified();
  canvas->Update();
}
