// Display an autogenerated fit-plot macro with only its main distribution.
// The source macro is executed as-is; no bin-content or pull assignments are
// read or modified.
#include <stdexcept>

#include "TCanvas.h"
#include "TList.h"
#include "TPad.h"
#include "TROOT.h"
#include "TH1.h"

void display_without_pull(const char *inputMacro)
{
  gROOT->ProcessLine(Form(".x %s", inputMacro));

  TCanvas *canvas =
      dynamic_cast<TCanvas *>(gROOT->GetListOfCanvases()->Last());
  if (!canvas)
    throw std::runtime_error("The input macro did not create a canvas");

  TPad *mainPad = dynamic_cast<TPad *>(canvas->GetListOfPrimitives()->FindObject("pad1"));
  TPad *pullPad = dynamic_cast<TPad *>(canvas->GetListOfPrimitives()->FindObject("pad2"));
  if (!mainPad || !pullPad)
    throw std::runtime_error("Expected a pad1 main panel and pad2 pull panel");

  // Promote the existing main panel to the whole canvas, retaining every
  // histogram, fitted curve, legend, and label created by the source macro.
  mainPad->SetPad(0.0, 0.0, 1.0, 1.0);
  mainPad->SetTopMargin(0.08);
  mainPad->SetBottomMargin(0.13);
  mainPad->cd();

  TIter next(mainPad->GetListOfPrimitives());
  TH1 *mainHistogram = nullptr;
  while (TObject *object = next()) {
    mainHistogram = dynamic_cast<TH1 *>(object);
    if (mainHistogram)
      break;
  }
  if (mainHistogram) {
    mainHistogram->GetXaxis()->SetLabelSize(0.045);
    mainHistogram->GetXaxis()->SetTitleSize(0.055);
    mainHistogram->GetXaxis()->SetTitleOffset(0.95);
  }

  canvas->cd();
  canvas->GetListOfPrimitives()->Remove(pullPad);
  delete pullPad;
  canvas->Modified();
  canvas->Update();
}
