// Run in a separate ROOT process so two autogenerated macros that both
// define mc_2D() can be handled without modifying either source file.
#include <stdexcept>
#include <fstream>
#include <string>

#include "TCanvas.h"
#include "TBox.h"
#include "TFile.h"
#include "TList.h"
#include "TROOT.h"
#include "TH2.h"

namespace {
TH2 *FindTH2(TPad *pad)
{
  TIter next(pad->GetListOfPrimitives());
  while (TObject *object = next()) {
    if (TH2 *histogram = dynamic_cast<TH2 *>(object))
      return histogram;
    if (TPad *subpad = dynamic_cast<TPad *>(object)) {
      if (TH2 *histogram = FindTH2(subpad))
        return histogram;
    }
  }
  return nullptr;
}

void WriteTBoxes(TPad *pad, TFile &output, int &boxIndex)
{
  TIter next(pad->GetListOfPrimitives());
  while (TObject *object = next()) {
    if (TBox *box = dynamic_cast<TBox *>(object))
      box->Write(Form("comparison_box_%d", boxIndex++));
    else if (TPad *subpad = dynamic_cast<TPad *>(object))
      WriteTBoxes(subpad, output, boxIndex);
  }
}
} // namespace

void extract_mc_2D_histogram(const char *inputMacro, const char *outputFile)
{
  // Only inspect the function declaration at the start of the autogenerated
  // macro. Some files have a filename that does not match their function.
  std::ifstream macro(inputMacro);
  std::string line;
  std::string functionName;
  for (int lineCount = 0; lineCount < 20 && std::getline(macro, line); ++lineCount) {
    const std::size_t declaration = line.find("void ");
    if (declaration == std::string::npos)
      continue;
    const std::size_t nameBegin = declaration + 5;
    const std::size_t nameEnd = line.find('(', nameBegin);
    if (nameEnd != std::string::npos)
      functionName = line.substr(nameBegin, nameEnd - nameBegin);
    break;
  }
  if (functionName.empty())
    throw std::runtime_error(Form("Could not identify macro function in %s", inputMacro));

  gROOT->LoadMacro(inputMacro);
  gROOT->ProcessLine(Form("%s()", functionName.c_str()));
  TCanvas *canvas =
      dynamic_cast<TCanvas *>(gROOT->GetListOfCanvases()->Last());
  if (!canvas)
    throw std::runtime_error(Form("Could not retrieve canvas from %s", inputMacro));
  TH2 *source = canvas ? FindTH2(canvas) : nullptr;

  TFile output(outputFile, "RECREATE");
  if (source) {
    source->Write("mc2D");
    int boxIndex = 0;
    WriteTBoxes(canvas, output, boxIndex);
    return;
  }

  TPad *mainPad = dynamic_cast<TPad *>(
      canvas->GetListOfPrimitives()->FindObject("pad1"));
  if (!mainPad)
    throw std::runtime_error(Form("Could not retrieve a TH2 or main pad from %s", inputMacro));
  mainPad->Write("mainPad");
}
