#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

if [[ -n ${SSH_CONNECTION:-} && -n ${TMUX:-} ]]; then
  while IFS= read -r client_pid; do
    [[ -r "/proc/$client_pid/environ" ]] || continue
    while IFS= read -r -d '' entry; do
      case "$entry" in
        DISPLAY=*) export DISPLAY=${entry#DISPLAY=} ;;
        XAUTHORITY=*) export XAUTHORITY=${entry#XAUTHORITY=} ;;
      esac
    done < "/proc/$client_pid/environ"
    [[ -n ${DISPLAY:-} ]] && break
  done < <(tmux list-clients -F '#{client_pid}' 2>/dev/null)
fi

[[ $# -eq 5 ]] || { printf 'Expected macro path plus xmin ymin xmax ymax\n' >&2; exit 2; }

YAZI_ROOT_HELPERS_DIR="$script_dir" YAZI_ZOOM_MACRO="$1" YAZI_XMIN="$2" YAZI_YMIN="$3" YAZI_XMAX="$4" YAZI_YMAX="$5" root.exe -l -e '
  gInterpreter->Declare("void yazi_root_canvas_closed() { gROOT->SetInterrupt(); }");
  const char *helpersDir = gSystem->Getenv("YAZI_ROOT_HELPERS_DIR");
  if (!helpersDir) gSystem->Exit(2);
  gROOT->LoadMacro(Form("%s/display_zoomed_autogenerated.C", helpersDir));
  display_zoomed_autogenerated(gSystem->Getenv("YAZI_ZOOM_MACRO"),
    TString(gSystem->Getenv("YAZI_XMIN")).Atof(), TString(gSystem->Getenv("YAZI_YMIN")).Atof(),
    TString(gSystem->Getenv("YAZI_XMAX")).Atof(), TString(gSystem->Getenv("YAZI_YMAX")).Atof());
  TCanvas *canvas = (TCanvas *)gROOT->GetListOfCanvases()->Last();
  if (!canvas) gSystem->Exit(1);
  canvas->Connect("Closed()", 0, 0, "yazi_root_canvas_closed()");
  while (!gSystem->ProcessEvents()) gSystem->Sleep(100);
'
