#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

# Use the active tmux client's X11 environment after SSH reconnects.
if [[ -n ${SSH_CONNECTION:-} && -n ${TMUX:-} ]]; then
  while IFS= read -r client_pid; do
    [[ -r "/proc/$client_pid/environ" ]] || continue
    while IFS= read -r -d '' entry; do
      case "$entry" in
        DISPLAY=*) export DISPLAY=${entry#DISPLAY=} ;;
        XAUTHORITY=*) export XAUTHORITY=${entry#XAUTHORITY=} ;;
      esac
    done < "/proc/$client_pid/environ"
    [[ -n ${DISPLAY:-} ]] && break
  done < <(tmux list-clients -F '#{client_pid}' 2>/dev/null)
fi

(( $# >= 2 && $# % 2 == 0 )) || {
  printf 'Select an even number of autogenerated 2D ROOT macros (one pair per comparison)\n' >&2
  exit 2
}

open_pair() {
  YAZI_ROOT_HELPERS_DIR="$script_dir" YAZI_TOP_MACRO="$1" YAZI_BOTTOM_MACRO="$2" root.exe -l -e '
  gInterpreter->Declare("void yazi_root_canvas_closed() { gROOT->SetInterrupt(); }");
  const char *helpersDir = gSystem->Getenv("YAZI_ROOT_HELPERS_DIR");
  if (!helpersDir) gSystem->Exit(2);
  gROOT->LoadMacro(Form("%s/compare_mc_2D.C", helpersDir));
  compare_autogenerated(gSystem->Getenv("YAZI_TOP_MACRO"),
                        gSystem->Getenv("YAZI_BOTTOM_MACRO"));
  TCanvas *canvas = (TCanvas *)gROOT->GetListOfCanvases()->Last();
  if (!canvas) gSystem->Exit(1);
  canvas->Connect("Closed()", 0, 0, "yazi_root_canvas_closed()");
  while (!gSystem->ProcessEvents()) gSystem->Sleep(100);
'
}

pids=()
while (( $# )); do
  open_pair "$1" "$2" &
  pids+=("$!")
  shift 2
done

status=0
for pid in "${pids[@]}"; do
  wait "$pid" || status=$?
done
exit "$status"
